server:
  port: 8888
spring:
  application:
    name: 'main-service'
  datasource:
    url: jdbc:postgresql://localhost:5432/academy
    username: manager
    password: manager
  jpa:
    show-sql: true
student:
  backendServiceHost: localhost
  backendServicePort: 8080
info:
  application-name: ${spring.application.name}
  developer:
    name: Homer Simpson
    email: homer@simpson.com
management.endpoints.web.exposure.include: '*'

